export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINE = "GET_MEDICINE"
export const POST_MEDICINE = "POST_MEDICINE"
export const DELETE_MEDICINE = "DELETE_MEDICINE"
export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const ERROR_MEDICINE = "ERROR_MEDICINE"

export const GET_DOCTORS = "GET_DOCTORS"
